[[plugins]]
repo = "cespare/vim-toml"
on_ft = ["toml"]

[[plugins]]
repo = "godlygeek/tabular"
on_ft = [ "markdown" ]

[[plugins]]
repo = "plasticboy/vim-markdown"
depends = [ "tabular" ]
on_ft = [ "markdown" ]
hook_add = """
let g:vim_markdown_folding_disabled = 1
let g:vim_markdown_override_foldtext = 0
let g:vim_markdown_conceal = 0
"""

[[plugins]] # markdownを集中して書く系のやつ
repo = "junegunn/goyo.vim"
on_ft = [ "markdown" ]

[[plugins]] # markdownを集中して書く系のやつ
repo = "junegunn/limelight.vim"
depends = [ "goyo.vim" ]
on_ft = [ "markdown" ]

[[plugins]]
repo = "dhruvasagar/vim-table-mode"
hook_add = """
let g:table_mode_corner = '|'
"""

[[plugins]]
repo = "Shougo/deoplete.nvim"
[[plugins]]
repo = "Shougo/denite.nvim"
depends = [ "deoplete.nvim" ]

[[plugins]]
repo = "prettier/vim-prettier"
on_ft = ["javascript", "typescript"]

[[plugins]]
repo = "alvan/vim-closetag"
on_ft = ["html", "vue", "javascript", "typescript", "erb"]
hook_add = """
let g:closetag_filenames = '*.html,*.vue,*.erb'
"""

[[plugins]]
repo = "HerringtonDarkholme/yats.vim"
on_ft = ["typescript"]

#[[plugins]]
#repo = "mhartington/nvim-typescript"
#build = "install.sh"
#on_ft = ["typescript"]

[[plugins]]
repo = "elzr/vim-json"
depends = [ "Yggdroot/indentLine" ]
on_ft = ["json"]
hook_add = """
let g:vim_json_syntax_conceal = 0
"""

[[plugins]]
repo = "posva/vim-vue"
on_ft = [ "vue" ]

[[plugins]]
repo = "mechatroner/rainbow_csv"
on_ft = [ "csv", "tsv" ]

[[plugins]]
repo = "tpope/vim-dadbod"

[[plugins]]
repo = "zah/nim.vim"
on_ft = [ "nim" ]

[[plugins]]
repo = "alaviss/nim.nvim"
on_ft = [ "nim" ]

[[plugins]]
repo = "vmchale/dhall-vim"
on_ft = [ "dhall" ]
