[[plugins]]
repo = "Shougo/dein.vim"

[[plugins]]
repo = "editorconfig/editorconfig-vim"

[[plugins]]
repo = "neoclide/coc.nvim"
merge = 0
rev = "release"

[[plugins]]
repo = "w0rp/ale"
hook_add = """
let g:ale_fixers = {
\   'ruby': ['rubocop'],
\}
"""

[[plugins]]
repo = "itchyny/lightline.vim"
[[plugins]]
repo = 'maximbaz/lightline-ale'
depends = [ "lightline.vim", "ale" ]

[[plugins]]
repo = "tpope/vim-fugitive"
[[plugins]]
repo = "airblade/vim-gitgutter"
depends = [ "vim-fugitive" ]

[[plugins]]
repo = "easymotion/vim-easymotion"

[[plugins]]
repo = "Shougo/defx.nvim"

[[plugins]]
repo = "Yggdroot/indentLine"
hook_add = """
let g:indentLine_color_gui = '#A4E57E'
let g:indentLine_char_list = ['|', '¦', '┆', '┊']
"""
